### ISSUE TITLE
Installation issue: fs.opener.errors.UnsupportedProtocol: protocol 's3' is not supported

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/s3fs#15]
I installed fs=2.0.16 and s3fs inside Python 3.6 venv:

```
ajung@dev ~/src/s3 $ bin/pip freeze
appdirs==1.4.3
boto3==1.4.7
botocore==1.7.47
docutils==0.14
fs==2.0.16
jmespath==0.9.3
python-dateutil==2.6.1
pytz==2017.3
s3fs==0.1.2
s3transfer==0.1.11
six==1.11.0
ajung@dev ~/src/s3 $ bin/python
Python 3.6.2 (default, Jul 19 2017, 07:36:50) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fs import open_fs
>>> s3fs = open_fs('s3://mybucket')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ajung/src/s3/lib/python3.6/site-packages/fs/opener/registry.py", line 179, in open_fs
    default_protocol=default_protocol
  File "/home/ajung/src/s3/lib/python3.6/site-packages/fs/opener/registry.py", line 136, in open
    opener = self.get_opener(protocol)
  File "/home/ajung/src/s3/lib/python3.6/site-packages/fs/opener/registry.py", line 75, in get_opener
    "protocol '{}' is not supported".format(protocol)
fs.opener.errors.UnsupportedProtocol: protocol 's3' is not supported
```

**Comment by willmcgugan** [comment]
The package is `fs-s3`.

`s3fs` is not a a PyFilesystem class, AFAIK.
