### ISSUE TITLE
tree() and walk() don't work with minio

### ISSUE THREAD

**Issue by pitrou** [PyFilesystem/s3fs#57]
I have a file in `somedir/subdir`:
```
>>> list(fs.listdir('somedir/subdir'))                                                                                                                               
['mkpass.py']
```

However neither walk() nor tree() are able to see it:
```
>>> list(fs.walk('somedir/subdir'))                                                                                                                                  
Traceback (most recent call last):
  File "<ipython-input-39-f399f0a633b1>", line 1, in <module>
    list(fs.walk('somedir/subdir'))
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fs/walk.py", line 337, in walk
    for dir_path, info in _walk:
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fs/walk.py", line 433, in _walk_breadth
    for info in _scan(fs, dir_path, namespaces=namespaces):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fs/walk.py", line 298, in _scan
    six.reraise(type(error), error)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
ResourceNotFound: resource '/somedir/subdir' not found

>>> fs.tree()                                                                                                                                                        
├── somedir
│   └── error (resource '/somedir' not found)
└── bench-amd.txt
```

**Comment by willmcgugan** [comment]
Last time I tested Minio it wasn't fully compatible with S3 and was too much work to support. However, I suspect your issue may be related to [this](https://fs-s3fs.readthedocs.io/en/latest/#limitations).

**Comment by pitrou** [comment]
This is possible. To be honest, I'm an S3 newbie. However, I notice that `listdir` works (see above).

**Comment by mrk-its** [comment]
> This is possible. To be honest, I'm an S3 newbie. However, I notice that `listdir` works (see above).

`listdir` works because it do not check if parent directory exists as `scandir` does, take a look on my PR referenced above. BTW `listdir` implementation should simply call `scandir` and only transform result to list of filenames, I'll create separate PR for that.
